storage.trainees.file.path=file:src/main/resources/data/trainees.json
storage.trainers.file.path=file:src/main/resources/data/trainees.json
storage.trainings.file.path=file:src/main/resources/data/trainees.json
